version: "3.5"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxdatamx_api
    #env_file:
    #  - ".back.env"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
